name = "givers/main"
version = "0.1.0"
description = "Main codebase for Givers"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"
generate_interfaces = ".pesde/scripts/generate_interfaces.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
charm = { wally = "littensy/charm", version = "0.10.0" }
charm-sync = { wally = "littensy/charm-sync", version = "0.3.0" }
react = { wally = "jsdotlua/react", version = "17.2.1" }
react-roblox = { wally = "jsdotlua/react-roblox", version = "17.2.1" }
react-charm = { wally = "littensy/react-charm", version = "0.3.0" }
ripple = { wally = "littensy/ripple", version = "0.9.3" }
ui-labs = { wally = "pepeeltoro41/ui-labs", version = "2.3.8" }
sift = { wally = "csqrl/sift", version = "0.0.11" }
t = { wally = "osyrisrblx/t", version = "3.1.1" }
profilestore = { wally = "lm-loleris/profilestore", version = "^1.0.3" }
testez = { wally = "roblox/testez", version = "0.4.1" }
janitor = { wally = "howmanysmall/janitor", version = "1.18.3" }

promise = { wally = "evaera/promise", version = "4.0.0" }
typed-luau-promise = { wally = "trheliad/typed-luau-promise", version = "1.0.0" }
jecs = { wally = "ukendio/jecs", version = "0.9.0" }
jabby = { wally = "alicesaidhi/jabby", version = "0.4.0" }
planck = { wally = "yetanotherclown/planck", version = "0.2.0" }